version: '3.8'

services:
  api:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
